"""Initial migrate

Revision ID: d57d2bf6ed07
Revises: f23ddcd7b836
Create Date: 2022-01-30 17:34:53.135469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd57d2bf6ed07'
down_revision = 'f23ddcd7b836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('save_route_id', sa.Integer(), nullable=True),
    sa.Column('save_stop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['save_route_id'], ['routes.route_id'], ),
    sa.ForeignKeyConstraint(['save_stop_id'], ['stops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('stops', sa.Column('direction', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stops', 'direction')
    op.drop_table('users')
    # ### end Alembic commands ###
