"""empty message

Revision ID: f23ddcd7b836
Revises: 
Create Date: 2022-01-16 18:30:26.499195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f23ddcd7b836'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_stop', sa.String(length=256), nullable=True),
    sa.Column('width_map', sa.Float(), nullable=True),
    sa.Column('longitude_map', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('start_stop', sa.Integer(), nullable=True),
    sa.Column('finish_stop', sa.Integer(), nullable=True),
    sa.Column('count_minibus', sa.Integer(), nullable=True),
    sa.Column('count_stops', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['finish_stop'], ['stops.id'], ),
    sa.ForeignKeyConstraint(['start_stop'], ['stops.id'], ),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_table('stoproute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('stop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stoproute')
    op.drop_table('routes')
    op.drop_table('stops')
    # ### end Alembic commands ###
